openapi: 3.0.0 
info:
  title: Spaghetti Cooking API test simon
  version: 1.0.0
  description: API for cooking spaghetti
servers:
  - url: https://api.example.com
paths:
  /cookSpaghetti:
    post:
      summary: Cook spaghetti
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                waterTemperature:
                  type: integer
                  description: Temperature of the water in degrees Celsius
                pastaQuantity:
                  type: integer
                  description: Quantity of pasta in grams
                cookingTime:
                  type: integer
                  description: Cooking time in seconds
      responses:
        200:
          description: Spaghetti cooked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the spaghetti is cooked successfully
                  message:
                    type: string
                    description: A message describing the cooking result
                  isAlDente:
                    type: boolean
                    description: Indicates whether the spaghetti is cooked al dente
                  isOvercooked:
                    type: boolean
                    description: Indicates whether the spaghetti is overcooked
        400:
          description: Bad request
        500:
          description: Internal server error
